<?php


namespace app\admin\model;

class Classify extends Base
{
    protected $name = 'classify';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}